include("createRoutes.jl")
include("solvers.jl")
include("pricing.jl")
include("createRCRoutes.jl")
include("gap.jl")
include("solutionUtils.jl")
include("reporting.jl")
include("columnGeneration.jl")

main(200, 1, 10, 1, 500; pricingMinParallel=16, pricingMaxParallel=20, ramLevel1=0.55, ramLevel2=0.68, ramLevel3=0.78, ramLevel4=0.88, pricingLaunchDelay=0.15, dominanceMaxKeysFast=50000, dominanceMaxKeysExact=2000000, compatibilityBoundFast=true, compatibilityBoundExact=true, flag=0)